<a href="https://colab.research.google.com/github/manutd-1878/Data-Science-Bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Norma wektora, długość wektora w R2**

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [6]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1) # norma wektora

np.float64(4.123105625617661)

# **Norma euklidesowa w Rn**

In [9]:
v2 =np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

# **Odległość dwóch punktów na płaszczyźnie**

In [11]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)


np.float64(5.0)

# **Odległość dwóch punktów w przestzreni Rn**

In [12]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)


np.float64(5.0990195135927845)

# **Mnożenie macierzy**

In [18]:
#Przykład_1 liczba kolumny macierzy X(po lewej) jest rózna liczbie wierszy
#macierzy Y(po prawej), mnożenie mozliwe
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [16]:
Z = np.dot(X, Y)
Z


array([[ 2],
       [-6]])

In [19]:
Z.shape

(2, 1)

In [20]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [21]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [22]:
Z.shape

(2, 3)

# **Wyznacznik macierzy**

In [23]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

# **Ślad macierzy**

In [24]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.trace(A))

5

# **Macierz jednostkowa**

In [25]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# **Macierz odwrotna**

In [26]:
A

array([[ 2,  4],
       [-1,  3]])

In [27]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [28]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [29]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

# **Macierz transponowana**

In [30]:
A

array([[ 2,  4],
       [-1,  3]])

In [31]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [32]:
A.T

array([[ 2, -1],
       [ 4,  3]])

# **Rozwiązywanie układów równań**

In [33]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [34]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [35]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [36]:
X.shape

(2, 1)